sonar.projectKey=Bahmni_bahmni-core
sonar.organization=bahmni
sonar.projectName=bahmni-core

sonar.sources=.
sonar.exclusions=**/target/**,**/node_modules/**
sonar.java.binaries=**/target/classes

sonar.coverage.jacoco.xmlReportPaths=**/target/site/jacoco/jacoco.xml

sonar.sourceEncoding=UTF-8
