apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: cms
  name: mysql-pv-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi  # Must match the capacity specified in your PV
  storageClassName: efs-sc  # Use the StorageClass created earlier

