apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: cms
  name: mysql-pv-volume
spec:
  capacity:
    storage: 10Gi  # Adjust as per your requirements
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany  # Use ReadWriteMany for EFS
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc  # Use the StorageClass created earlier
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-08834a9041b587ee8  # Replace with your EFS File System ID

