name: Bahmni-Core - Github actions

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        ruby: [2.5]

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
      - uses: actions/setup-java@v1
        with:
            java-version: 1.8

      - name: Set up Ruby      
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - run: gem install compass 
      - run: mvn clean package

      - uses: actions/upload-artifact@v2
        with:
            name: Bahmnicore
            path: bahmnicore-omod/target/bahmnicore-omod-0.94-SNAPSHOT.jar
        

